version: "3.8"

services:

  redis:
    image: redis:7.2
    restart: always
    #ports:
    #  - "6379:6379"
    volumes:
      - redis-data:/data
    deploy:
      replicas: 1

  stomp-relay:
    image: soi23-game-stomp-relay:1.0
    #ports:
    #  - "61613:61613"
    restart: always

  web-server:
    image: soi23-game-web-server:1.0
    restart: always
    environment:
      - SPRING_DATA_REDIS_HOST=redis
    deploy:
      replicas: 2

  ui:
    image: soi23-game-ui:1.0
    restart: always
    ports:
      - "80:80"
    # - "4200:80"

volumes:
  redis-data:
